add_subdirectory(fallback_path)
add_subdirectory(fast_stop_trajectory_fallback)
add_subdirectory(lane_borrow_path)
add_subdirectory(lane_borrow_path_generic)
add_subdirectory(lane_change_path)
add_subdirectory(lane_change_path_generic)
add_subdirectory(lane_follow_path)
add_subdirectory(obstacle_nudge_decider)
add_subdirectory(open_space_fallback_decider)
add_subdirectory(open_space_fallback_decider_park)
add_subdirectory(open_space_path_planning)
add_subdirectory(open_space_pre_stop_decider)
add_subdirectory(open_space_replan_decider)
add_subdirectory(open_space_roi_decider)
add_subdirectory(open_space_roi_decider_park)
add_subdirectory(open_space_trajectory_optimizer_park)
add_subdirectory(open_space_trajectory_partition)
add_subdirectory(open_space_trajectory_post_process)
add_subdirectory(open_space_trajectory_provider)
add_subdirectory(path_decider)
add_subdirectory(path_reference_decider)
add_subdirectory(path_time_heuristic)
add_subdirectory(piecewise_jerk_speed)
add_subdirectory(piecewise_jerk_speed_nonlinear)
add_subdirectory(pull_over_path)
add_subdirectory(reuse_path)
add_subdirectory(reverse_path)
add_subdirectory(reverse_speed)
add_subdirectory(rss_decider)
add_subdirectory(rule_based_stop_decider)
add_subdirectory(smooth_stop_trajectory_fallback)
add_subdirectory(speed_bounds_decider)
add_subdirectory(speed_decider)
add_subdirectory(square_path)
add_subdirectory(st_bounds_decider)
