# ============================================================================
# modules/prediction_plugin/CMakeLists.txt
# Prediction Plugin Models
# ============================================================================

add_subdirectory(semantic_lstm_pedestrian_tensorrt)
add_subdirectory(semantic_lstm_vehicle_tensorrt)
add_subdirectory(multi_agent_pedestrian_tensorrt)
add_subdirectory(multi_agent_vehicle_tensorrt)
