add_subdirectory(bare_intersection_unprotected)
add_subdirectory(emergency_pull_over)
add_subdirectory(emergency_stop)
add_subdirectory(free_space)
add_subdirectory(lane_escape)
add_subdirectory(lane_follow)
add_subdirectory(lane_follow_park)
add_subdirectory(large_curvature)
add_subdirectory(park_and_go)
add_subdirectory(precise_parking)
add_subdirectory(pull_over)
add_subdirectory(square)
add_subdirectory(stop_sign_unprotected)
add_subdirectory(traffic_light_protected)
add_subdirectory(traffic_light_unprotected_left_turn)
add_subdirectory(traffic_light_unprotected_right_turn)
add_subdirectory(valet_parking)
add_subdirectory(valet_parking_park)
add_subdirectory(yield_sign)